parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint/eslint-plugin"
  - "simple-import-sort"
  - "security-node"
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:security-node/recommended
env:
  node: true
  jest: true
rules:
  "@typescript-eslint/adjacent-overload-signatures": 1
  "@typescript-eslint/no-var-requires": 0
  "@typescript-eslint/no-unused-vars": 2
  "simple-import-sort/sort": 1
  eqeqeq: 2
  no-console: 2
  no-debugger: 2
  no-duplicate-imports: 2
  no-else-return: 2
  no-empty-function:
    - 2
    - allow:
      - constructors
  no-extra-boolean-cast: 1
  no-multi-spaces: 2
  no-unreachable: 2
  indent:
    - 2
    - 2
    - SwitchCase: 1
  key-spacing:
    - 2
    - mode: strict
  prefer-template: 1
  require-await: 2
